services:
  mongo:
    image: mongo:6
    container_name: cv-builder-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: cv-builder-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/cv-builder
    depends_on:
      - mongo

volumes:
  mongo-data:
