version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cv-builder
      - NODE_ENV=development
    depends_on:
      - mongo
volumes:
mongo-data:
